language: node_js

node_js:
  - '12'

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  global:
    # **Staging**: surge (`Surge.sh`)
    # SURGE_LOGIN
    - secure: "TODO"
    # SURGE_TOKEN
    - secure: "TODO"

install:
  - yarn install --frozen-lockfile

notifications:
  email:
    on_success: change
    on_failure: always

script:
  # Build all packages for production
  - yarn run build
  # All other checks.
  - yarn run check

jobs:
  include:
    - stage: deployment
      node_js: '12'
      script:
        - echo "TODO STAGING DEPLOY"
        - ls packages/*/dist || echo "NO DIST"
      deploy:
        # Deploy master to production
        - provider: script
          script: >-
            echo "TODO PROD DEPLOY"
          skip_cleanup: true
          on:
            branch: master
