language: node_js

node_js:
  - '12'

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  global:
    # **Staging**: surge (`Surge.sh`)
    # SURGE_LOGIN
    - secure: "TODO"
    # SURGE_TOKEN
    - secure: "TODO"

install:
  - yarn install --frozen-lockfile

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - yarn run check

jobs:
  include:
    - stage: deployment
      node_js: '12'
      script:
        # Deploy PR to staging
        - yarn clean
        - yarn deploy
      deploy:
        # Deploy master to production
        - provider: script
          script: >-
            yarn clean &&
            PROD=true yarn deploy
          skip_cleanup: true
          on:
            branch: master
